### ISSUE TITLE
Filing Access Failure: Crashing with ValueError on date parse

### ISSUE THREAD

**Issue by chuhanyi03** [dgunning/edgartools#457]
## Issue Type

- [ ] Data Quality Issue (incorrect financial values, missing data)
- [ ] XBRL Parsing Issue (statement rendering, concept mapping)  
- [x] Filing Access Issue (download failures, attachment problems)
- [ ] Performance Issue (slow operations, memory problems)
- [ ] Compatibility Issue (platform/dependency conflicts)
- [ ] Documentation Issue (unclear instructions, missing examples)

## Environment
**EdgarTools Version:** 4.18.0 (also in 4.17.1)
**Python Version:** 3.12.11
**Operating System:**  Windows 11

## Bug Description
**What you expected to happen:**
**In short, I hope these codes run normally without reporting errors.** 

**What actually happened:**
The library tried to parse this HTML and crashed with a ValueError because it found a date string it couldn't understand. It found a date string in my local language (Chinese) on the HTML page and crashed with a ValueError because the date format did not match what it expected. This error was misleading and made it very difficult to diagnose the real network problem. I tried in vain to change the network environment and force the locale to set an English time language environment, in an effort to ensure that the dates in the HTTP headers could be correctly parsed.

**Error message (if any):**
```
ValueError: time data '周五, 10 10月 2025 11:57:10 GMT' does not match format '%a, %d %b %Y %H:%M:%S GMT'
And it was displayed as follows once ValueError: 
time data 'Fri, 10 Oct 2025 10:54:12 GMT' does not match format '%a, %d %b %Y %H:%M:%S GMT'
And sometimes I find that the time displayed by the error message does not match the actual time. 
```

## Reproduction
**Company/Ticker:**  AAPL
**Time Period:** N/A. The issue occurs during the Company("AAPL") object initialization, before fetching filings for **any specific time period** .
**Relevant Forms:** all forms

**Minimal code to reproduce:**
```python

from edgar import Company
# method 1
apple = Company("AAPL")
filings = apple.get_filings(form="10-K")

#or method 2
form4_filings = get_filings(form="4")
form4 = form4_filings[0].obj()

#or method 3
filing = apple.latest("10-K")
tenk = filing.obj()

```

## Additional Context

<img width="1840" height="507" alt="Image" src="https://github.com/user-attachments/assets/1194c667-858a-4b7e-9569-069c2d74fd57" />

<img width="1796" height="811" alt="Image" src="https://github.com/user-attachments/assets/23421c56-6d64-446b-8848-d121a03c75fa" />

---

**Comment by dgunning** [comment]
## Root Cause Identified

This issue is caused by a bug in the `httpxthrottlecache` library (a dependency of EdgarTools). The library uses `time.strptime()` to parse HTTP date headers, which is locale-dependent. On systems with non-English locales (Chinese, Japanese, German, French, etc.), the date parsing fails because month and day names are in the local language format.

**Location in httpxthrottlecache:**
`httpxthrottlecache/filecache/transport.py` uses:
```python
time.strptime(last_modified, "%a, %d %b %Y %H:%M:%S GMT")
```

When your system locale is set to Chinese, the parsed date becomes `'周五, 10 10月 2025'` (Friday, October in Chinese) instead of `'Fri, 10 Oct 2025'`.

## Actions Taken

### 1. Upstream Issue Filed
We've prepared a detailed issue report for the httpxthrottlecache maintainer with proposed fixes. The recommended solution is to use `email.utils.parsedate_to_datetime()` which is locale-independent and designed for HTTP date headers.

### 2. Workaround Implemented in EdgarTools
Since this affects all EdgarTools users with non-English locales, we've implemented a workaround in `edgar/httpclient.py` that forces the `LC_TIME` locale to 'C' before importing httpxthrottlecache. This ensures HTTP date parsing uses English month/day names regardless of system locale.

**Fix:**
```python
# Force C locale for httpxthrottlecache to avoid locale-dependent date parsing
try:
    locale.setlocale(locale.LC_TIME, 'C')
except (locale.Error, ValueError):
    pass

from httpxthrottlecache import HttpxThrottleCache
```

### 3. Testing
✅ Tested with reproduction script simulating Chinese locale
✅ All operations work correctly (Company creation, filing retrieval)
✅ No ValueError on date parsing

## Resolution

This fix will be included in the next EdgarTools release. You should no longer experience this issue after upgrading.

Thank you for the detailed bug report and for helping us identify this locale-dependent behavior!

**Comment by chuhanyi03** [comment]
Thank you for looking into it.

**Comment by dgunning** [comment]
Fixed in Release 4.19.0

**Comment by chuhanyi03** [comment]
Thank you so much for your quick response and for releasing a new version to address this issue. I really appreciate you taking the time to work on it! 

Unfortunately, it seems the problem still persists on my end after updating to the latest version. I'm still encountering the same ValueError.

The error message is:

`ValueError: time data '周五, 10 10月 2025 11:57:10 GMT' does not match format '%a, %d %b %Y %H:%M:%S GMT'
`

I also noticed that the timestamp in the error message, '周五, 10 10月 2025 11:57:10 GMT', seems to be static and does not change over time.

To provide more context, I tested the code on Google Colab, and it runs perfectly there without any errors. This makes me strongly suspect the issue is specific to my local machine's environment, but the free tier of Colab is too slow for my needs, so I'd really like to get it working locally.

It's possible this could be an issue specific to my local environment, but I'd really like to get it working on my machine.  Could you suggest what I should check on my end to diagnose this?  I doubted that whether the cache somewhere hasn't been removed completely, but I have no idea how to check and solve it. 

I've spent a lot of time trying many ways and even changed many language Settings from Chinese to English, but unfortunately in vain. Any guidance you could provide would be extremely helpful.

Thanks again for your hard work.

**Comment by chuhanyi03** [comment]
Here's the traceback, if needed.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[4], [line 3](vscode-notebook-cell:?execution_count=4&line=3)
      1 c = Company("AAPL")  # Apple Inc.
----> [3](vscode-notebook-cell:?execution_count=4&line=3) new_filings = c.get_filings(form="4")[0]
      5 tenk = new_filings.obj()
      7 print(tenk)

File d:\BOAT_YI\Download\Miniconda3\Lib\site-packages\edgar\entity\core.py:239, in Entity.get_filings(self, year, quarter, form, accession_number, file_number, filing_date, date, amendments, is_xbrl, is_inline_xbrl, sort_by, trigger_full_load)
    212 """
    213 Get the entity's filings and optionally filter by multiple criteria.
    214 
   (...)
    235     Filtered filings matching the criteria
    236 """
    237 # Simply delegate to the EntityData implementation
    238 # This preserves the lazy-loading behavior while keeping the API clean
--> [239](file:///D:/BOAT_YI/Download/Miniconda3/Lib/site-packages/edgar/entity/core.py:239) return self.data.get_filings(
    240     year=year,
    241     quarter=quarter,
    242     form=form,
    243     accession_number=accession_number,
    244     file_number=file_number,
    245     filing_date=filing_date or date,
    246     amendments=amendments,
    247     is_xbrl=is_xbrl,
    248     is_inline_xbrl=is_inline_xbrl,
    249     sort_by=sort_by,
    250     trigger_full_load=trigger_full_load
    251 )

File d:\BOAT_YI\Download\Miniconda3\Lib\site-packages\edgar\entity\core.py:372, in Company.data(self)
    369 """Get detailed data for this company."""
    370 # For simplicity, return the base EntityData
    371 # Type checkers will still see this as a CompanyData due to the annotation
--> [372](file:///D:/BOAT_YI/Download/Miniconda3/Lib/site-packages/edgar/entity/core.py:372) return super().data

File d:\BOAT_YI\Download\Miniconda3\Lib\functools.py:998, in cached_property.__get__(self, instance, owner)
    996 val = cache.get(self.attrname, _NOT_FOUND)
    997 if val is _NOT_FOUND:
--> [998](file:///D:/BOAT_YI/Download/Miniconda3/Lib/functools.py:998)     val = self.func(instance)
    999     try:
   1000         cache[self.attrname] = val

File d:\BOAT_YI\Download\Miniconda3\Lib\site-packages\edgar\entity\core.py:138, in Entity.data(self)
    135 from edgar.entity.submissions import get_entity_submissions
    137 # get_entity_submissions returns the EntityData directly
--> [138](file:///D:/BOAT_YI/Download/Miniconda3/Lib/site-packages/edgar/entity/core.py:138) entity_data = get_entity_submissions(self.cik)
    140 if entity_data:
    141     self._data = entity_data

File d:\BOAT_YI\Download\Miniconda3\Lib\site-packages\edgar\entity\submissions.py:107, in get_entity_submissions(cik)
    105         submissions_json = download_entity_submissions_from_sec(cik)
    106 else:
--> [107](file:///D:/BOAT_YI/Download/Miniconda3/Lib/site-packages/edgar/entity/submissions.py:107)     submissions_json = download_entity_submissions_from_sec(cik)
    108 if submissions_json:
    109     return parse_entity_submissions(submissions_json)

File d:\BOAT_YI\Download\Miniconda3\Lib\site-packages\edgar\entity\submissions.py:80, in download_entity_submissions_from_sec(cik)
     70 """
     71 Get the company filings for a given cik.
     72 
   (...)
     77     Optional[Dict[str, Any]]: The entity submissions JSON data, or None if not found
     78 """
     79 try:
---> [80](file:///D:/BOAT_YI/Download/Miniconda3/Lib/site-packages/edgar/entity/submissions.py:80)     submission_json = download_json(f"https://data.sec.gov/submissions/CIK{cik:010}.json")
     81 except httpx.HTTPStatusError as e:
     82     # Handle the case where the cik is invalid and not found on Edgar
     83     if e.response.status_code == 404:

File d:\BOAT_YI\Download\Miniconda3\Lib\site-packages\edgar\httprequests.py:578, in download_json(data_url)
    568 def download_json(data_url: str) -> dict:
    569     """
    570     Download JSON data from a URL.
    571 
   (...)
    576         dict: The parsed JSON data.
    577     """
--> [578](file:///D:/BOAT_YI/Download/Miniconda3/Lib/site-packages/edgar/httprequests.py:578)     content = download_file(data_url, as_text=True)
    579     return json.loads(content)

File d:\BOAT_YI\Download\Miniconda3\Lib\site-packages\edgar\httprequests.py:374, in download_file(url, as_text, path)
    370 if as_text is None:
    371     # Set the default based on the file extension
    372     as_text = url.endswith(text_extensions)
--> [374](file:///D:/BOAT_YI/Download/Miniconda3/Lib/site-packages/edgar/httprequests.py:374) response = get_with_retry(url=url)
    375 inspect_response(response)
    377 if not as_text:
    378     # Set the default to true if the url ends with a text extension

File d:\BOAT_YI\Download\Miniconda3\Lib\site-packages\stamina\_core.py:752, in retry.<locals>.retry_decorator.<locals>.sync_inner(*args, **kw)
    750 @wraps(wrapped)
    751 def sync_inner(*args: P.args, **kw: P.kwargs) -> T:  # type: ignore[return]
--> [752](file:///D:/BOAT_YI/Download/Miniconda3/Lib/site-packages/stamina/_core.py:752)     for attempt in retry_ctx.with_name(  # noqa: RET503
    753         name, args, kw
    754     ):
    755         with attempt:
    756             return wrapped(*args, **kw)

File d:\BOAT_YI\Download\Miniconda3\Lib\site-packages\stamina\_core.py:525, in _RetryContextIterator.__iter__(self)
    519     return
    521 before_sleep = _make_before_sleep(
    522     self._name, CONFIG, self._args, self._kw, self._cms_to_exit
    523 )
--> [525](file:///D:/BOAT_YI/Download/Miniconda3/Lib/site-packages/stamina/_core.py:525) for r in _t.Retrying(
    526     before=self._exit_cms,
    527     before_sleep=before_sleep,
    528     **self._apply_maybe_test_mode_to_tenacity_kw(CONFIG.testing),
    529 ):
    530     yield Attempt(r, self._backoff_for_attempt_number)

File d:\BOAT_YI\Download\Miniconda3\Lib\site-packages\tenacity\__init__.py:445, in BaseRetrying.__iter__(self)
    443 retry_state = RetryCallState(self, fn=None, args=(), kwargs={})
    444 while True:
--> [445](file:///D:/BOAT_YI/Download/Miniconda3/Lib/site-packages/tenacity/__init__.py:445)     do = self.iter(retry_state=retry_state)
    446     if isinstance(do, DoAttempt):
    447         yield AttemptManager(retry_state=retry_state)

File d:\BOAT_YI\Download\Miniconda3\Lib\site-packages\tenacity\__init__.py:378, in BaseRetrying.iter(self, retry_state)
    376 result = None
    377 for action in self.iter_state.actions:
--> [378](file:///D:/BOAT_YI/Download/Miniconda3/Lib/site-packages/tenacity/__init__.py:378)     result = action(retry_state)
    379 return result

File d:\BOAT_YI\Download\Miniconda3\Lib\site-packages\tenacity\__init__.py:400, in BaseRetrying._post_retry_check_actions.<locals>.<lambda>(rs)
    398 def _post_retry_check_actions(self, retry_state: "RetryCallState") -> None:
    399     if not (self.iter_state.is_explicit_retry or self.iter_state.retry_run_result):
--> [400](file:///D:/BOAT_YI/Download/Miniconda3/Lib/site-packages/tenacity/__init__.py:400)         self._add_action_func(lambda rs: rs.outcome.result())
    401         return
    403     if self.after is not None:

File d:\BOAT_YI\Download\Miniconda3\Lib\concurrent\futures\_base.py:449, in Future.result(self, timeout)
    447     raise CancelledError()
    448 elif self._state == FINISHED:
--> [449](file:///D:/BOAT_YI/Download/Miniconda3/Lib/concurrent/futures/_base.py:449)     return self.__get_result()
    451 self._condition.wait(timeout)
    453 if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:

File d:\BOAT_YI\Download\Miniconda3\Lib\concurrent\futures\_base.py:401, in Future.__get_result(self)
    399 if self._exception:
    400     try:
--> [401](file:///D:/BOAT_YI/Download/Miniconda3/Lib/concurrent/futures/_base.py:401)         raise self._exception
    402     finally:
    403         # Break a reference cycle with the exception in self._exception
    404         self = None

File d:\BOAT_YI\Download\Miniconda3\Lib\site-packages\stamina\_core.py:756, in retry.<locals>.retry_decorator.<locals>.sync_inner(*args, **kw)
    752 for attempt in retry_ctx.with_name(  # noqa: RET503
    753     name, args, kw
    754 ):
    755     with attempt:
--> [756](file:///D:/BOAT_YI/Download/Miniconda3/Lib/site-packages/stamina/_core.py:756)         return wrapped(*args, **kw)

File d:\BOAT_YI\Download\Miniconda3\Lib\site-packages\edgar\httprequests.py:101, in with_identity.<locals>.wrapper(url, identity, identity_callable, *args, **kwargs)
     98 headers["User-Agent"] = identity
     99 kwargs["headers"] = headers
--> [101](file:///D:/BOAT_YI/Download/Miniconda3/Lib/site-packages/edgar/httprequests.py:101) return func(url, identity=identity, identity_callable=identity_callable, *args, **kwargs)

File d:\BOAT_YI\Download\Miniconda3\Lib\site-packages\edgar\httprequests.py:152, in get_with_retry(url, identity, identity_callable, **kwargs)
    136 """
    137 Sends a GET request with retry functionality and identity handling.
    138 
   (...)
    149     TooManyRequestsError: If the response status code is 429 (Too Many Requests).
    150 """
    151 with http_client() as client:
--> [152](file:///D:/BOAT_YI/Download/Miniconda3/Lib/site-packages/edgar/httprequests.py:152)     response = client.get(url, **kwargs)
    153     if response.status_code == 429:
    154         raise TooManyRequestsError(url)

File d:\BOAT_YI\Download\Miniconda3\Lib\site-packages\httpx\_client.py:1053, in Client.get(self, url, params, headers, cookies, auth, follow_redirects, timeout, extensions)
   1036 def get(
   1037     self,
   1038     url: URL | str,
   (...)
   1046     extensions: RequestExtensions | None = None,
   1047 ) -> Response:
   1048     """
   1049     Send a `GET` request.
   1050 
   1051     **Parameters**: See `httpx.request`.
   1052     """
-> [1053](file:///D:/BOAT_YI/Download/Miniconda3/Lib/site-packages/httpx/_client.py:1053)     return self.request(
   1054         "GET",
   1055         url,
   1056         params=params,
   1057         headers=headers,
   1058         cookies=cookies,
   1059         auth=auth,
   1060         follow_redirects=follow_redirects,
   1061         timeout=timeout,
   1062         extensions=extensions,
   1063     )

File d:\BOAT_YI\Download\Miniconda3\Lib\site-packages\httpx\_client.py:825, in Client.request(self, method, url, content, data, files, json, params, headers, cookies, auth, follow_redirects, timeout, extensions)
    810     warnings.warn(message, DeprecationWarning, stacklevel=2)
    812 request = self.build_request(
    813     method=method,
    814     url=url,
   (...)
    823     extensions=extensions,
    824 )
--> [825](file:///D:/BOAT_YI/Download/Miniconda3/Lib/site-packages/httpx/_client.py:825) return self.send(request, auth=auth, follow_redirects=follow_redirects)

File d:\BOAT_YI\Download\Miniconda3\Lib\site-packages\httpx\_client.py:914, in Client.send(self, request, stream, auth, follow_redirects)
    910 self._set_timeout(request)
    912 auth = self._build_request_auth(request, auth)
--> [914](file:///D:/BOAT_YI/Download/Miniconda3/Lib/site-packages/httpx/_client.py:914) response = self._send_handling_auth(
    915     request,
    916     auth=auth,
    917     follow_redirects=follow_redirects,
    918     history=[],
    919 )
    920 try:
    921     if not stream:

File d:\BOAT_YI\Download\Miniconda3\Lib\site-packages\httpx\_client.py:942, in Client._send_handling_auth(self, request, auth, follow_redirects, history)
    939 request = next(auth_flow)
    941 while True:
--> [942](file:///D:/BOAT_YI/Download/Miniconda3/Lib/site-packages/httpx/_client.py:942)     response = self._send_handling_redirects(
    943         request,
    944         follow_redirects=follow_redirects,
    945         history=history,
    946     )
    947     try:
    948         try:

File d:\BOAT_YI\Download\Miniconda3\Lib\site-packages\httpx\_client.py:979, in Client._send_handling_redirects(self, request, follow_redirects, history)
    976 for hook in self._event_hooks["request"]:
    977     hook(request)
--> [979](file:///D:/BOAT_YI/Download/Miniconda3/Lib/site-packages/httpx/_client.py:979) response = self._send_single_request(request)
    980 try:
    981     for hook in self._event_hooks["response"]:

File d:\BOAT_YI\Download\Miniconda3\Lib\site-packages\httpx\_client.py:1014, in Client._send_single_request(self, request)
   1009     raise RuntimeError(
   1010         "Attempted to send an async request with a sync Client instance."
   1011     )
   1013 with request_context(request=request):
-> [1014](file:///D:/BOAT_YI/Download/Miniconda3/Lib/site-packages/httpx/_client.py:1014)     response = transport.handle_request(request)
   1016 assert isinstance(response.stream, SyncByteStream)
   1018 response.request = request

File d:\BOAT_YI\Download\Miniconda3\Lib\site-packages\hishel\_sync\_transports.py:114, in CacheTransport.handle_request(self, request)
    100 httpcore_request = httpcore.Request(
    101     method=request.method,
    102     url=httpcore.URL(
   (...)
    110     extensions=request.extensions,
    111 )
    113 key = self._controller._key_generator(httpcore_request, body_for_key)
--> [114](file:///D:/BOAT_YI/Download/Miniconda3/Lib/site-packages/hishel/_sync/_transports.py:114) stored_data = self._storage.retrieve(key)
    116 request_cache_control = parse_cache_control(
    117     extract_header_values_decoded(request.headers.raw, b"Cache-Control")
    118 )
    120 if request_cache_control.only_if_cached and not stored_data:

File d:\BOAT_YI\Download\Miniconda3\Lib\site-packages\hishel\_sync\_storages.py:211, in FileStorage.retrieve(self, key)
    209         read_data = self._file_manager.read_from(str(response_path))
    210         if len(read_data) != 0:
--> [211](file:///D:/BOAT_YI/Download/Miniconda3/Lib/site-packages/hishel/_sync/_storages.py:211)             return self._serializer.loads(read_data)
    212 return None

File d:\BOAT_YI\Download\Miniconda3\Lib\site-packages\httpxthrottlecache\serializer.py:85, in JSONByteSerializer.loads(self, data)
     83 request_dict = full_json["request"]
     84 metadata_dict = full_json["metadata"]
---> [85](file:///D:/BOAT_YI/Download/Miniconda3/Lib/site-packages/httpxthrottlecache/serializer.py:85) metadata_dict["created_at"] = datetime.strptime(
     86     metadata_dict["created_at"],
     87     "%a, %d %b %Y %H:%M:%S GMT",
     88 )
     90 response = Response(
     91     status=response_dict["status"],
     92     headers=[
   (...)
    101     },
    102 )
    104 request = Request(
    105     method=request_dict["method"],
    106     url=request_dict["url"],
   (...)
    112     },
    113 )

File d:\BOAT_YI\Download\Miniconda3\Lib\_strptime.py:653, in _strptime_datetime(cls, data_string, format)
    650 def _strptime_datetime(cls, data_string, format="%a %b %d %H:%M:%S %Y"):
    651     """Return a class cls instance based on the input string and the
    652     format string."""
--> [653](file:///D:/BOAT_YI/Download/Miniconda3/Lib/_strptime.py:653)     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
    654     tzname, gmtoff = tt[-2:]
    655     args = tt[:6] + (fraction,)

File d:\BOAT_YI\Download\Miniconda3\Lib\_strptime.py:432, in _strptime(data_string, format)
    430 found = format_regex.match(data_string)
    431 if not found:
--> [432](file:///D:/BOAT_YI/Download/Miniconda3/Lib/_strptime.py:432)     raise ValueError("time data %r does not match format %r" %
    433                      (data_string, format))
    434 if len(data_string) != found.end():
    435     raise ValueError("unconverted data remains: %s" %
    436                       data_string[found.end():])

ValueError: time data '周五, 10 10月 2025 11:57:10 GMT' does not match format '%a, %d %b %Y %H:%M:%S GMT'
```

**Comment by dgunning** [comment]
## Investigating Reopened Issue

Thank you for reporting that the issue persists. I'm investigating the root cause and will coordinate with the product manager for proper classification and resolution.

**Initial Analysis:**
The fix in 4.19.0 addresses locale-dependent date parsing for NEW HTTP requests, but the error you're seeing is coming from a different location - when reading OLD cached data that was created BEFORE the fix was applied.

**Root Cause:**
Looking at your traceback, the error occurs in:
```
File .../httpxthrottlecache/serializer.py:85 in JSONByteSerializer.loads
    metadata_dict["created_at"] = datetime.strptime(
        metadata_dict["created_at"],
        "%a, %d %b %Y %H:%M:%S GMT",
    )
```

The cache files created when your system was using Chinese locale contain timestamps like `'周五, 10 10月 2025 11:57:10 GMT'`. When the serializer tries to load these cached responses, it fails to parse the Chinese date format.

**Immediate Workaround:**
Please try clearing your cache directory and restarting:
```python
from edgar.core import get_edgar_data_dir
from pathlib import Path
import shutil

cache_dir = Path(get_edgar_data_dir()) / "_tcache"
if cache_dir.exists():
    shutil.rmtree(cache_dir)
    print(f"Cleared cache at {cache_dir}")
```

Then restart your Python session and try again. This should force fresh requests that will be cached with proper English locale dates.

I'm coordinating with our product manager to determine the proper fix for this edge case.

**Comment by chuhanyi03** [comment]
Thank you for your timely reply! 

I just tried the code you mentioned and got an error:

`ImportError: cannot import name 'get_edgar_data_dir' from 'edgar.core'`

**Comment by dgunning** [comment]
## Issue #457 Resolution - Point Release 4.19.1

### Problem Analysis
The issue persisted after v4.19.0 because the locale fix only addressed **NEW** cache entries. Users who had **OLD** cache files from pre-4.19.0 installations (created with Chinese locale timestamps like '周五, 10 10月 2025 11:57:10 GMT') continued experiencing ValueError when these cached responses were deserialized.

### Root Cause
Two-part problem:
1. **4.19.0 fix**: Forced `LC_TIME='C'` before importing httpxthrottlecache (prevents NEW cache corruption)
2. **Remaining issue**: OLD cache files with Chinese timestamps still existed and failed to deserialize

### Solution Implemented
Automatic one-time cache clearing with marker file:

**New Function**: `clear_locale_corrupted_cache()` in `edgar/httpclient.py`
- Checks for marker file `.locale_fix_457_applied`
- Clears HTTP cache directory if marker doesn't exist
- Creates marker file to prevent repeated clearing
- Called automatically on `import edgar` (one-time operation)

**User Experience**:
1. User upgrades to v4.19.1
2. Imports edgar: `from edgar import Company`
3. Cache automatically cleared in background (< 100ms)
4. Subsequent imports skip clearing (marker file exists)
5. All operations work correctly with fresh cache

### Testing
Comprehensive test suite (`test_issue_457_locale_cache_fix.py`):
- ✅ 10 tests, all passing
- Cache clearing on first run
- Marker file prevents repeated clearing
- Error handling for permission issues
- User upgrade workflow validation
- Locale independence verification

### Verification
```bash
# Run tests
pytest tests/issues/regression/test_issue_457_locale_cache_fix.py -v
======================== 10 passed ========================
```

### Files Modified
1. `edgar/httpclient.py` - Added `clear_locale_corrupted_cache()` function (57 lines)
2. `edgar/__init__.py` - Added automatic cache clearing on import (7 lines)
3. `CHANGELOG.md` - Added v4.19.1 release notes
4. `tests/issues/regression/test_issue_457_locale_cache_fix.py` - Comprehensive test suite (255 lines)

### Release Ready
- ✅ Fix implemented and tested
- ✅ All tests passing (10/10)
- ✅ CHANGELOG updated for v4.19.1
- ✅ Ready for point release

**Next Steps**: Coordinate with product-manager for v4.19.1 point release within 2 hours (P0 EMERGENCY timeline).

@chuhanyi03 - Please try the fix by upgrading to v4.19.1 when released. The cache clearing will happen automatically on your first import.

**Comment by chuhanyi03** [comment]
That's fantastic, thank you so much! I'm really impressed by how quickly you've addressed this.

I truly appreciate your hard work on edgartools and I'm looking forward to the v4.19.1 release.

Thanks again!

**Comment by dgunning** [comment]
## ✅ Fixed in v4.19.1

This issue has been resolved and released in **v4.19.1**.

### The Fix

The v4.19.0 fix prevented **new** cache corruption by forcing `LC_TIME='C'` before importing httpxthrottlecache. However, users with **old** corrupted cache files (created before v4.19.0 with locale-specific timestamps) still experienced errors.

v4.19.1 adds an automatic one-time cache clearing system:
- Checks for marker file `.locale_fix_457_applied`
- Clears HTTP cache directory if marker doesn't exist
- Creates marker file to prevent repeated clearing
- Completely transparent to users (< 100ms on first import)

### User Experience

After upgrading to v4.19.1:
```python
from edgar import Company  # Cache automatically cleared in background
c = Company("AAPL")        # Works perfectly - no errors!
```

### Timeline

- **Classification**: P0 EMERGENCY (complete functionality failure for international users)
- **Implementation**: 1h 45m from classification to PyPI release
- **Release**: v4.19.1 published to PyPI and GitHub

### Verification

Please upgrade to v4.19.1 and verify the issue is resolved:
```bash
pip install --upgrade edgartools
```

Thank you for reporting this critical issue!

**Release**: https://github.com/dgunning/edgartools/releases/tag/v4.19.1

**Comment by Orgron** [comment]
Hi, I'm getting this same error on 4.19.1 on Russian locale.

```---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[4], [line 1](vscode-notebook-cell:?execution_count=4&line=1)
----> [1](vscode-notebook-cell:?execution_count=4&line=1) filings = company.get_filings(form="8-K", trigger_full_load=True, amendments=False)

File c:\Users\mrsel\miniforge3\envs\director-peer-effects\Lib\site-packages\edgar\entity\core.py:239, in Entity.get_filings(self, year, quarter, form, accession_number, file_number, filing_date, date, amendments, is_xbrl, is_inline_xbrl, sort_by, trigger_full_load)
    212 """
    213 Get the entity's filings and optionally filter by multiple criteria.
    214 
   (...)
    235     Filtered filings matching the criteria
    236 """
    237 # Simply delegate to the EntityData implementation
    238 # This preserves the lazy-loading behavior while keeping the API clean
--> [239](file:///C:/Users/mrsel/miniforge3/envs/director-peer-effects/Lib/site-packages/edgar/entity/core.py:239) return self.data.get_filings(
    240     year=year,
    241     quarter=quarter,
    242     form=form,
    243     accession_number=accession_number,
    244     file_number=file_number,
    245     filing_date=filing_date or date,
    246     amendments=amendments,
    247     is_xbrl=is_xbrl,
    248     is_inline_xbrl=is_inline_xbrl,
    249     sort_by=sort_by,
    250     trigger_full_load=trigger_full_load
    251 )

File c:\Users\mrsel\miniforge3\envs\director-peer-effects\Lib\site-packages\edgar\entity\core.py:372, in Company.data(self)
    369 """Get detailed data for this company."""
    370 # For simplicity, return the base EntityData
    371 # Type checkers will still see this as a CompanyData due to the annotation
--> [372](file:///C:/Users/mrsel/miniforge3/envs/director-peer-effects/Lib/site-packages/edgar/entity/core.py:372) return super().data

File c:\Users\mrsel\miniforge3\envs\director-peer-effects\Lib\functools.py:995, in cached_property.__get__(self, instance, owner)
    993 val = cache.get(self.attrname, _NOT_FOUND)
    994 if val is _NOT_FOUND:
--> [995](file:///C:/Users/mrsel/miniforge3/envs/director-peer-effects/Lib/functools.py:995)     val = self.func(instance)
    996     try:
    997         cache[self.attrname] = val

File c:\Users\mrsel\miniforge3\envs\director-peer-effects\Lib\site-packages\edgar\entity\core.py:138, in Entity.data(self)
    135 from edgar.entity.submissions import get_entity_submissions
    137 # get_entity_submissions returns the EntityData directly
--> [138](file:///C:/Users/mrsel/miniforge3/envs/director-peer-effects/Lib/site-packages/edgar/entity/core.py:138) entity_data = get_entity_submissions(self.cik)
    140 if entity_data:
    141     self._data = entity_data

File c:\Users\mrsel\miniforge3\envs\director-peer-effects\Lib\site-packages\edgar\entity\submissions.py:107, in get_entity_submissions(cik)
    105         submissions_json = download_entity_submissions_from_sec(cik)
    106 else:
--> [107](file:///C:/Users/mrsel/miniforge3/envs/director-peer-effects/Lib/site-packages/edgar/entity/submissions.py:107)     submissions_json = download_entity_submissions_from_sec(cik)
    108 if submissions_json:
    109     return parse_entity_submissions(submissions_json)

File c:\Users\mrsel\miniforge3\envs\director-peer-effects\Lib\site-packages\edgar\entity\submissions.py:80, in download_entity_submissions_from_sec(cik)
     70 """
     71 Get the company filings for a given cik.
     72 
   (...)
     77     Optional[Dict[str, Any]]: The entity submissions JSON data, or None if not found
     78 """
     79 try:
---> [80](file:///C:/Users/mrsel/miniforge3/envs/director-peer-effects/Lib/site-packages/edgar/entity/submissions.py:80)     submission_json = download_json(f"https://data.sec.gov/submissions/CIK{cik:010}.json")
     81 except httpx.HTTPStatusError as e:
     82     # Handle the case where the cik is invalid and not found on Edgar
     83     if e.response.status_code == 404:

File c:\Users\mrsel\miniforge3\envs\director-peer-effects\Lib\site-packages\edgar\httprequests.py:578, in download_json(data_url)
    568 def download_json(data_url: str) -> dict:
    569     """
    570     Download JSON data from a URL.
    571 
   (...)
    576         dict: The parsed JSON data.
    577     """
--> [578](file:///C:/Users/mrsel/miniforge3/envs/director-peer-effects/Lib/site-packages/edgar/httprequests.py:578)     content = download_file(data_url, as_text=True)
    579     return json.loads(content)

File c:\Users\mrsel\miniforge3\envs\director-peer-effects\Lib\site-packages\edgar\httprequests.py:374, in download_file(url, as_text, path)
    370 if as_text is None:
    371     # Set the default based on the file extension
    372     as_text = url.endswith(text_extensions)
--> [374](file:///C:/Users/mrsel/miniforge3/envs/director-peer-effects/Lib/site-packages/edgar/httprequests.py:374) response = get_with_retry(url=url)
    375 inspect_response(response)
    377 if not as_text:
    378     # Set the default to true if the url ends with a text extension

File c:\Users\mrsel\miniforge3\envs\director-peer-effects\Lib\site-packages\stamina\_core.py:752, in retry.<locals>.retry_decorator.<locals>.sync_inner(*args, **kw)
    750 @wraps(wrapped)
    751 def sync_inner(*args: P.args, **kw: P.kwargs) -> T:  # type: ignore[return]
--> [752](file:///C:/Users/mrsel/miniforge3/envs/director-peer-effects/Lib/site-packages/stamina/_core.py:752)     for attempt in retry_ctx.with_name(  # noqa: RET503
    753         name, args, kw
    754     ):
    755         with attempt:
    756             return wrapped(*args, **kw)

File c:\Users\mrsel\miniforge3\envs\director-peer-effects\Lib\site-packages\stamina\_core.py:525, in _RetryContextIterator.__iter__(self)
    519     return
    521 before_sleep = _make_before_sleep(
    522     self._name, CONFIG, self._args, self._kw, self._cms_to_exit
    523 )
--> [525](file:///C:/Users/mrsel/miniforge3/envs/director-peer-effects/Lib/site-packages/stamina/_core.py:525) for r in _t.Retrying(
    526     before=self._exit_cms,
    527     before_sleep=before_sleep,
    528     **self._apply_maybe_test_mode_to_tenacity_kw(CONFIG.testing),
    529 ):
    530     yield Attempt(r, self._backoff_for_attempt_number)

File c:\Users\mrsel\miniforge3\envs\director-peer-effects\Lib\site-packages\tenacity\__init__.py:445, in BaseRetrying.__iter__(self)
    443 retry_state = RetryCallState(self, fn=None, args=(), kwargs={})
    444 while True:
--> [445](file:///C:/Users/mrsel/miniforge3/envs/director-peer-effects/Lib/site-packages/tenacity/__init__.py:445)     do = self.iter(retry_state=retry_state)
    446     if isinstance(do, DoAttempt):
    447         yield AttemptManager(retry_state=retry_state)

File c:\Users\mrsel\miniforge3\envs\director-peer-effects\Lib\site-packages\tenacity\__init__.py:378, in BaseRetrying.iter(self, retry_state)
    376 result = None
    377 for action in self.iter_state.actions:
--> [378](file:///C:/Users/mrsel/miniforge3/envs/director-peer-effects/Lib/site-packages/tenacity/__init__.py:378)     result = action(retry_state)
    379 return result

File c:\Users\mrsel\miniforge3\envs\director-peer-effects\Lib\site-packages\tenacity\__init__.py:400, in BaseRetrying._post_retry_check_actions.<locals>.<lambda>(rs)
    398 def _post_retry_check_actions(self, retry_state: "RetryCallState") -> None:
    399     if not (self.iter_state.is_explicit_retry or self.iter_state.retry_run_result):
--> [400](file:///C:/Users/mrsel/miniforge3/envs/director-peer-effects/Lib/site-packages/tenacity/__init__.py:400)         self._add_action_func(lambda rs: rs.outcome.result())
    401         return
    403     if self.after is not None:

File c:\Users\mrsel\miniforge3\envs\director-peer-effects\Lib\concurrent\futures\_base.py:449, in Future.result(self, timeout)
    447     raise CancelledError()
    448 elif self._state == FINISHED:
--> [449](file:///C:/Users/mrsel/miniforge3/envs/director-peer-effects/Lib/concurrent/futures/_base.py:449)     return self.__get_result()
    451 self._condition.wait(timeout)
    453 if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:

File c:\Users\mrsel\miniforge3\envs\director-peer-effects\Lib\concurrent\futures\_base.py:401, in Future.__get_result(self)
    399 if self._exception:
    400     try:
--> [401](file:///C:/Users/mrsel/miniforge3/envs/director-peer-effects/Lib/concurrent/futures/_base.py:401)         raise self._exception
    402     finally:
    403         # Break a reference cycle with the exception in self._exception
    404         self = None

File c:\Users\mrsel\miniforge3\envs\director-peer-effects\Lib\site-packages\stamina\_core.py:756, in retry.<locals>.retry_decorator.<locals>.sync_inner(*args, **kw)
    752 for attempt in retry_ctx.with_name(  # noqa: RET503
    753     name, args, kw
    754 ):
    755     with attempt:
--> [756](file:///C:/Users/mrsel/miniforge3/envs/director-peer-effects/Lib/site-packages/stamina/_core.py:756)         return wrapped(*args, **kw)

File c:\Users\mrsel\miniforge3\envs\director-peer-effects\Lib\site-packages\edgar\httprequests.py:101, in with_identity.<locals>.wrapper(url, identity, identity_callable, *args, **kwargs)
     98 headers["User-Agent"] = identity
     99 kwargs["headers"] = headers
--> [101](file:///C:/Users/mrsel/miniforge3/envs/director-peer-effects/Lib/site-packages/edgar/httprequests.py:101) return func(url, identity=identity, identity_callable=identity_callable, *args, **kwargs)

File c:\Users\mrsel\miniforge3\envs\director-peer-effects\Lib\site-packages\edgar\httprequests.py:152, in get_with_retry(url, identity, identity_callable, **kwargs)
    136 """
    137 Sends a GET request with retry functionality and identity handling.
    138 
   (...)
    149     TooManyRequestsError: If the response status code is 429 (Too Many Requests).
    150 """
    151 with http_client() as client:
--> [152](file:///C:/Users/mrsel/miniforge3/envs/director-peer-effects/Lib/site-packages/edgar/httprequests.py:152)     response = client.get(url, **kwargs)
    153     if response.status_code == 429:
    154         raise TooManyRequestsError(url)

File c:\Users\mrsel\miniforge3\envs\director-peer-effects\Lib\site-packages\httpx\_client.py:1053, in Client.get(self, url, params, headers, cookies, auth, follow_redirects, timeout, extensions)
   1036 def get(
   1037     self,
   1038     url: URL | str,
   (...)
   1046     extensions: RequestExtensions | None = None,
   1047 ) -> Response:
   1048     """
   1049     Send a `GET` request.
   1050 
   1051     **Parameters**: See `httpx.request`.
   1052     """
-> [1053](file:///C:/Users/mrsel/miniforge3/envs/director-peer-effects/Lib/site-packages/httpx/_client.py:1053)     return self.request(
   1054         "GET",
   1055         url,
   1056         params=params,
   1057         headers=headers,
   1058         cookies=cookies,
   1059         auth=auth,
   1060         follow_redirects=follow_redirects,
   1061         timeout=timeout,
   1062         extensions=extensions,
   1063     )

File c:\Users\mrsel\miniforge3\envs\director-peer-effects\Lib\site-packages\httpx\_client.py:825, in Client.request(self, method, url, content, data, files, json, params, headers, cookies, auth, follow_redirects, timeout, extensions)
    810     warnings.warn(message, DeprecationWarning, stacklevel=2)
    812 request = self.build_request(
    813     method=method,
    814     url=url,
   (...)
    823     extensions=extensions,
    824 )
--> [825](file:///C:/Users/mrsel/miniforge3/envs/director-peer-effects/Lib/site-packages/httpx/_client.py:825) return self.send(request, auth=auth, follow_redirects=follow_redirects)

File c:\Users\mrsel\miniforge3\envs\director-peer-effects\Lib\site-packages\httpx\_client.py:914, in Client.send(self, request, stream, auth, follow_redirects)
    910 self._set_timeout(request)
    912 auth = self._build_request_auth(request, auth)
--> [914](file:///C:/Users/mrsel/miniforge3/envs/director-peer-effects/Lib/site-packages/httpx/_client.py:914) response = self._send_handling_auth(
    915     request,
    916     auth=auth,
    917     follow_redirects=follow_redirects,
    918     history=[],
    919 )
    920 try:
    921     if not stream:

File c:\Users\mrsel\miniforge3\envs\director-peer-effects\Lib\site-packages\httpx\_client.py:942, in Client._send_handling_auth(self, request, auth, follow_redirects, history)
    939 request = next(auth_flow)
    941 while True:
--> [942](file:///C:/Users/mrsel/miniforge3/envs/director-peer-effects/Lib/site-packages/httpx/_client.py:942)     response = self._send_handling_redirects(
    943         request,
    944         follow_redirects=follow_redirects,
    945         history=history,
    946     )
    947     try:
    948         try:

File c:\Users\mrsel\miniforge3\envs\director-peer-effects\Lib\site-packages\httpx\_client.py:979, in Client._send_handling_redirects(self, request, follow_redirects, history)
    976 for hook in self._event_hooks["request"]:
    977     hook(request)
--> [979](file:///C:/Users/mrsel/miniforge3/envs/director-peer-effects/Lib/site-packages/httpx/_client.py:979) response = self._send_single_request(request)
    980 try:
    981     for hook in self._event_hooks["response"]:

File c:\Users\mrsel\miniforge3\envs\director-peer-effects\Lib\site-packages\httpx\_client.py:1014, in Client._send_single_request(self, request)
   1009     raise RuntimeError(
   1010         "Attempted to send an async request with a sync Client instance."
   1011     )
   1013 with request_context(request=request):
-> [1014](file:///C:/Users/mrsel/miniforge3/envs/director-peer-effects/Lib/site-packages/httpx/_client.py:1014)     response = transport.handle_request(request)
   1016 assert isinstance(response.stream, SyncByteStream)
   1018 response.request = request

File c:\Users\mrsel\miniforge3\envs\director-peer-effects\Lib\site-packages\hishel\_sync\_transports.py:114, in CacheTransport.handle_request(self, request)
    100 httpcore_request = httpcore.Request(
    101     method=request.method,
    102     url=httpcore.URL(
   (...)
    110     extensions=request.extensions,
    111 )
    113 key = self._controller._key_generator(httpcore_request, body_for_key)
--> [114](file:///C:/Users/mrsel/miniforge3/envs/director-peer-effects/Lib/site-packages/hishel/_sync/_transports.py:114) stored_data = self._storage.retrieve(key)
    116 request_cache_control = parse_cache_control(
    117     extract_header_values_decoded(request.headers.raw, b"Cache-Control")
    118 )
    120 if request_cache_control.only_if_cached and not stored_data:

File c:\Users\mrsel\miniforge3\envs\director-peer-effects\Lib\site-packages\hishel\_sync\_storages.py:211, in FileStorage.retrieve(self, key)
    209         read_data = self._file_manager.read_from(str(response_path))
    210         if len(read_data) != 0:
--> [211](file:///C:/Users/mrsel/miniforge3/envs/director-peer-effects/Lib/site-packages/hishel/_sync/_storages.py:211)             return self._serializer.loads(read_data)
    212 return None

File c:\Users\mrsel\miniforge3\envs\director-peer-effects\Lib\site-packages\httpxthrottlecache\serializer.py:85, in JSONByteSerializer.loads(self, data)
     83 request_dict = full_json["request"]
     84 metadata_dict = full_json["metadata"]
---> [85](file:///C:/Users/mrsel/miniforge3/envs/director-peer-effects/Lib/site-packages/httpxthrottlecache/serializer.py:85) metadata_dict["created_at"] = datetime.strptime(
     86     metadata_dict["created_at"],
     87     "%a, %d %b %Y %H:%M:%S GMT",
     88 )
     90 response = Response(
     91     status=response_dict["status"],
     92     headers=[
   (...)
    101     },
    102 )
    104 request = Request(
    105     method=request_dict["method"],
    106     url=request_dict["url"],
   (...)
    112     },
    113 )

File c:\Users\mrsel\miniforge3\envs\director-peer-effects\Lib\_strptime.py:555, in _strptime_datetime(cls, data_string, format)
    552 def _strptime_datetime(cls, data_string, format="%a %b %d %H:%M:%S %Y"):
    553     """Return a class cls instance based on the input string and the
    554     format string."""
--> [555](file:///C:/Users/mrsel/miniforge3/envs/director-peer-effects/Lib/_strptime.py:555)     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
    556     tzname, gmtoff = tt[-2:]
    557     args = tt[:6] + (fraction,)

File c:\Users\mrsel\miniforge3\envs\director-peer-effects\Lib\_strptime.py:333, in _strptime(data_string, format)
    331 found = format_regex.match(data_string)
    332 if not found:
--> [333](file:///C:/Users/mrsel/miniforge3/envs/director-peer-effects/Lib/_strptime.py:333)     raise ValueError("time data %r does not match format %r" %
    334                      (data_string, format))
    335 if len(data_string) != found.end():
    336     raise ValueError("unconverted data remains: %s" %
    337                       data_string[found.end():])

ValueError: time data 'Пн, 13 окт 2025 16:49:21 GMT' does not match format '%a, %d %b %Y %H:%M:%S GMT'```

**Comment by Orgron** [comment]
The error disappeared after I deleted the `.edgar` folder from my user home directory

**Comment by dgunning** [comment]
I release a fix in 4.19.1 that cleared the cache when that functionality is accessed for the first time.

Clearing the cache manually (or simply deleting the folder) is another way

**Comment by chuhanyi03** [comment]
It works! I've updated to 4.19.1, and the problem is finally solved. The code now runs perfectly on my local machine without any ValueError.

I am honestly so impressed and grateful for how quickly you handled this. Your responsiveness and dedication are truly amazing. You've made my day!

Thank you once again for your incredible work on edgartools. It's a wonderful project, and your support is top-notch. Keep up the fantastic work! 

Have a great week!
